apiVersion: v1
appVersion: "2.0.2"
description: A Helm chart for Postgres database develop by @W360S TEAM, @SAASTOOLS @FXPHUCVINHFX on Kubernetes to simply for end-user easy to use. Required `name service` and `namespace` must be `postgres`
name: postgres
version: 2.0.2